# Generated by Django 5.0.6 on 2024-07-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='role',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='role',
            field=models.ManyToManyField(to='par.professionalrole'),
        ),
    ]
