# Generated by Django 5.0.6 on 2024-07-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0003_remove_vacancy_role_delete_professionalrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_currency',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_gross',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_to',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_from',
            field=models.CharField(max_length=10000),
        ),
    ]
