# Generated by Django 5.0.6 on 2024-07-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0004_remove_vacancy_salary_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='url',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
