# Generated by Django 5.0.6 on 2024-07-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0005_alter_vacancy_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='address',
            field=models.CharField(max_length=100000),
        ),
    ]
