# Generated by Django 5.0.6 on 2024-07-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0006_alter_vacancy_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='employer',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employer_url',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
